### ISSUE TITLE
got a proxy error when trying to make the example main.js  work

### ISSUE THREAD

**Issue by gispk47** [api-ai/apiai-nodejs-client#60]
got an error like this : "Error: connect ETIMEDOUT : ***.**:443"
seems got blocked by the gfw in china

**Comment by BUHARIMOHAMEDISMAIL** [comment]
I'm also getting the same error i don't know how to overcome it.
Any one fix this issue please let me know.

**Comment by gertjaap** [comment]
Having this too.

**Comment by sajjanhubale** [comment]
can you please let me know how to fix this error?

Error: connect ETIMEDOUT 35.190.15.252:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.190.15.252',
  port: 443 }

**Comment by Rajesh1306** [comment]
@gertjaap u managed to find a solution? if yes can share details on it as I am facing similar issue as yours.
