### ISSUE TITLE
ECONNREFUSED 54.192.188.124:443

### ISSUE THREAD

**Issue by voltermot** [api-ai/apiai-nodejs-client#66]
Code:
var apiai = require('apiai');
 
var app = apiai("Client access token");
 
var request = app.textRequest('help', {
    sessionId: 'unique-sesssion-id'
});
 
request.on('response', function(response) {
    console.log(response);
});
 
request.on('error', function(error) {
    console.log(error);
});
 
request.end();

Response:
{ Error: connect ECONNREFUSED 54.192.188.124:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '54.192.188.124',
  port: 443 }

Access token : tried both client and developer token individually but failed to fetch response.
session-id : initially i copied the session id from curl script that was generated(failed) , also tried to generate some random value for session id(failed again).

i am not sure what mistake i am doing. i need help in figuring out this connection issue.

**Comment by BUHARIMOHAMEDISMAIL** [comment]
I'm also getting the same error.
please let me know If u fix this issue.

**Comment by sajjanhubale** [comment]
i am also getting the same error.
Please advise how to fix this issue..

Error: connect ETIMEDOUT 35.190.15.252:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.190.15.252',
  port: 443 }

**Comment by waikeat** [comment]
Is this error fixed? Please advise whether this SDK works when I am using ngrok.

{ Error: connect ECONNREFUSED 35.190.15.252:443
at Object.exports._errnoException (util.js:1022:11)
at exports._exceptionWithHostPort (util.js:1045:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
code: 'ECONNREFUSED',
 errno: 'ECONNREFUSED',
syscall: 'connect',
address: '35.190.15.252',
port: 443 }

**Comment by BUHARIMOHAMEDISMAIL** [comment]
This your proxy blocking issue.
If you tried in open network system then it will work.

Thanks & Regards
Mohamed Ismail
